/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Datos.Fuentes;
import Datos.Mtd_Integracion;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class Integracion extends javax.swing.JFrame {

    private final Font FP;

    /**
     * Creates new form Integracion
     */
    public Integracion() {
        initComponents();
        FP = Fuentes.setFuente("/assets/font_1.ttf");
        setLocationRelativeTo(null);
        Lbl_1.setFont(FP);
        Lbl_2.setFont(FP);
        Lbl_3.setFont(FP);
        Lbl_4.setFont(FP);
        Trapecio.setFont(FP);
        Smps_1_3.setFont(FP);
        Smps_3_8.setFont(FP);
        A.setFont(FP);
        B.setFont(FP);
        N.setFont(FP);
        clc.setFont(FP);
        rsscalelabel.RSScaleLabel.setScaleLabel(icon_integral, "src/assets/icon_int.png");

        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_1 = new javax.swing.JLabel();
        funcion = new javax.swing.JTextField();
        icon_integral = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        A_Text = new javax.swing.JTextField();
        B = new javax.swing.JLabel();
        B_Text = new javax.swing.JTextField();
        N = new javax.swing.JLabel();
        N_Text = new javax.swing.JTextField();
        Smps_3_8 = new javax.swing.JLabel();
        Smps_1_3 = new javax.swing.JLabel();
        Trapecio = new javax.swing.JLabel();
        Lbl_4 = new javax.swing.JLabel();
        Lbl_3 = new javax.swing.JLabel();
        Lbl_2 = new javax.swing.JLabel();
        clc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(455, 720));
        setMinimumSize(new java.awt.Dimension(455, 720));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        Lbl_1.setText("Función a integrar");
        getContentPane().add(Lbl_1);
        Lbl_1.setBounds(18, 27, 140, 40);

        funcion.setBackground(new java.awt.Color(255, 255, 255));
        funcion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        funcion.setForeground(new java.awt.Color(0, 0, 0));
        funcion.setAlignmentY(5.0F);
        funcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(funcion);
        funcion.setBounds(170, 30, 260, 30);
        getContentPane().add(icon_integral);
        icon_integral.setBounds(30, 80, 400, 180);

        A.setText("A:");
        getContentPane().add(A);
        A.setBounds(200, 290, 20, 16);

        A_Text.setBackground(new java.awt.Color(255, 255, 255));
        A_Text.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        A_Text.setForeground(new java.awt.Color(0, 0, 0));
        A_Text.setAlignmentY(5.0F);
        A_Text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(A_Text);
        A_Text.setBounds(220, 285, 50, 30);

        B.setText("B:");
        getContentPane().add(B);
        B.setBounds(40, 290, 20, 16);

        B_Text.setBackground(new java.awt.Color(255, 255, 255));
        B_Text.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        B_Text.setForeground(new java.awt.Color(0, 0, 0));
        B_Text.setAlignmentY(5.0F);
        B_Text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(B_Text);
        B_Text.setBounds(60, 285, 50, 30);

        N.setText("N:");
        getContentPane().add(N);
        N.setBounds(360, 290, 20, 16);

        N_Text.setBackground(new java.awt.Color(255, 255, 255));
        N_Text.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        N_Text.setForeground(new java.awt.Color(0, 0, 0));
        N_Text.setAlignmentY(5.0F);
        N_Text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(N_Text);
        N_Text.setBounds(380, 285, 50, 30);

        Smps_3_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smps_3_8.setText("... Esperando función ...");
        getContentPane().add(Smps_3_8);
        Smps_3_8.setBounds(30, 560, 400, 30);

        Smps_1_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smps_1_3.setText("... Esperando función ...");
        getContentPane().add(Smps_1_3);
        Smps_1_3.setBounds(30, 480, 400, 30);

        Trapecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Trapecio.setText("... Esperando función ...");
        getContentPane().add(Trapecio);
        Trapecio.setBounds(30, 390, 400, 30);

        Lbl_4.setText("Regla de simpson 3/8 :");
        getContentPane().add(Lbl_4);
        Lbl_4.setBounds(30, 520, 180, 30);

        Lbl_3.setText("Regla de simpson 1/3 :");
        getContentPane().add(Lbl_3);
        Lbl_3.setBounds(30, 430, 180, 30);

        Lbl_2.setText("Regla de trapecio :");
        getContentPane().add(Lbl_2);
        Lbl_2.setBounds(30, 340, 180, 30);

        clc.setBackground(new java.awt.Color(255, 255, 255));
        clc.setForeground(new java.awt.Color(0, 0, 0));
        clc.setText("Calcular");
        clc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        clc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clcMouseExited(evt);
            }
        });
        getContentPane().add(clc);
        clc.setBounds(155, 620, 150, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clcMouseEntered
        clc.setForeground(Color.WHITE);
        clc.setBackground(Color.BLACK);
    }//GEN-LAST:event_clcMouseEntered

    private void clcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clcMouseExited
        clc.setForeground(Color.BLACK);
        clc.setBackground(Color.WHITE);
    }//GEN-LAST:event_clcMouseExited

    private void clcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clcMouseClicked
        Mtd_Integracion m = new Mtd_Integracion();
        double A = Double.parseDouble(A_Text.getText());
        double B = Double.parseDouble(B_Text.getText());
        int N = Integer.parseInt(N_Text.getText());
        if (A < B && A != B) {
            if (N % 3 != 0) {
                try {
                    Trapecio.setText("" + m.mtd_trapecio(A, B, N, funcion.getText()));
                    Smps_1_3.setText("" + m.mtd_smps_1_3(A, B, N, funcion.getText()));
                    Smps_3_8.setText("No se puede usar este metodo con la N tomada");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Ha habido un error de escritura, Puede que la funcion este mal escrita o falten datos");
                }
            } else {
                try {
                    Trapecio.setText("" + m.mtd_trapecio(A, B, N, funcion.getText()));
                    Smps_1_3.setText("" + m.mtd_smps_1_3(A, B, N, funcion.getText()));
                    Smps_3_8.setText("" + m.mtd_smps_3_8(A, B, N, funcion.getText()));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Ha habido un error de escritura, Puede que la funcion este mal escrita o falten datos");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ha habido un error de escritura, B no puede ser menor ni igual a A");

        }
    }//GEN-LAST:event_clcMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Integracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Integracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Integracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Integracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Integracion().setVisible(true);
            }
        });
        System.out.println("Obligame prro");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JTextField A_Text;
    private javax.swing.JLabel B;
    private javax.swing.JTextField B_Text;
    private javax.swing.JLabel Lbl_1;
    private javax.swing.JLabel Lbl_2;
    private javax.swing.JLabel Lbl_3;
    private javax.swing.JLabel Lbl_4;
    private javax.swing.JLabel N;
    private javax.swing.JTextField N_Text;
    private javax.swing.JLabel Smps_1_3;
    private javax.swing.JLabel Smps_3_8;
    private javax.swing.JLabel Trapecio;
    private javax.swing.JButton clc;
    private javax.swing.JTextField funcion;
    private javax.swing.JLabel icon_integral;
    // End of variables declaration//GEN-END:variables
}
