/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Datos.Expresion;
import Datos.Mtd_Raices;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.BorderLayout;
import java.io.IOException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardXYItemLabelGenerator;
import org.jfree.chart.labels.XYItemLabelGenerator;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 * df
 *
 * @author carlo
 */
public class Raices extends javax.swing.JFrame {

    /**
     * Creates new form Raices
     */
    public ChartPanel chartPanel;
    private static final int SIZE = 456;

    public Raices() throws Exception {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(btn_close, "src/assets/icon_close.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(btn_equal, "src/assets/icon_equal.png");
        XYDataset paresDeDatos = generarDatos("x", 0, 0);
        JFreeChart diagrama = crearDiagrama(paresDeDatos);
        chartPanel = new ChartPanel(diagrama);
        grafica.setLayout(new java.awt.BorderLayout());
        grafica.add(chartPanel, BorderLayout.CENTER);

        //Graficador g = new Graficador();
    }

    private XYDataset generarDatos(String eq, int r, double raiz) throws Exception {
        //le pasamos una funcion generadora f(x)
        XYSeries datos = new XYSeries("Linea Funcion");
        for (double x = r - 5; x <= r + 5; x += 1) {
            datos.add(x, f(x, eq));
        }
        XYSeries raizx = new XYSeries("Raiz");
        raizx.add(raiz, 0);
        raizx.add(0, 0);

        XYSeriesCollection conjuntoDatos = new XYSeriesCollection();
        conjuntoDatos.addSeries(datos);
        conjuntoDatos.addSeries(raizx);

        return conjuntoDatos;
    }

    private JFreeChart crearDiagrama(XYDataset conjuntoDatos) throws IOException {
        JFreeChart diag = ChartFactory.createXYLineChart(
                null, //Titulo Grafica
                "X", // Leyenda eje X
                "Y", // Leyenda eje Y
                conjuntoDatos, // Los datos
                PlotOrientation.VERTICAL, //orientacion
                false, // ver titulo de linea
                true, //tooltips
                false //URL
        );
        XYPlot xyplot = (XYPlot) diag.getPlot();
        xyplot.setBackgroundPaint(Color.white);
        xyplot.setDomainGridlinePaint(Color.white);
        xyplot.setRangeGridlinePaint(Color.white);
        xyplot.setRangeZeroBaselineVisible(true);
        xyplot.setDomainZeroBaselineVisible(true);
        xyplot.setOutlinePaint(Color.WHITE);
        XYLineAndShapeRenderer renderer = (XYLineAndShapeRenderer) xyplot.getRenderer();
        renderer.setSeriesLinesVisible(1, false);
        renderer.setSeriesShapesVisible(1, true);
        XYItemLabelGenerator xy = new StandardXYItemLabelGenerator();
//        renderer.setBaseItemLabelGenerator(xy);
//        renderer.setBaseItemLabelsVisible(true);
//        renderer.setBaseLinesVisible(true);
//        renderer.setBaseItemLabelsVisible(true);
        return diag;
    }

    //aqui definimos la funcion que desees, en esta caso la f(x) = 4sen(x)
    private double f(double x, String eq) throws Exception {
        Expresion e = new Expresion();
        double a = e.Evaluar(eq, x);
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grafica = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ecuacion = new javax.swing.JTextField();
        btn_equal = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_mtd_bi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_mtd_fp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_mtd_sc1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_mtd_sc2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);

        grafica.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Ingrese la ecuacion");

        ecuacion.setBackground(new java.awt.Color(255, 255, 255));
        ecuacion.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        ecuacion.setForeground(new java.awt.Color(0, 0, 0));
        ecuacion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ecuacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        ecuacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ecuacionKeyPressed(evt);
            }
        });

        btn_equal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_equalMouseClicked(evt);
            }
        });

        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Metodo biseccion");

        lbl_mtd_bi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_mtd_bi.setText("Esperando ecuacion...");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Metodo falsa posicion");

        lbl_mtd_fp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_mtd_fp.setText("Esperando ecuacion...");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Metodo secante");

        lbl_mtd_sc1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_mtd_sc1.setText("Esperando ecuacion...");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Metodo secante modificada");

        lbl_mtd_sc2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_mtd_sc2.setText("Esperando ecuacion...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_mtd_sc2)
                    .addComponent(lbl_mtd_fp)
                    .addComponent(lbl_mtd_bi)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(lbl_mtd_sc1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ecuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(grafica, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ecuacion)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_mtd_bi)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_mtd_fp)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_mtd_sc1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_mtd_sc2))
                    .addComponent(grafica, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        rsscalelabel.RSScaleLabel.setScaleLabel(btn_close, "src/assets/icon_close_focus.png");
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        rsscalelabel.RSScaleLabel.setScaleLabel(btn_close, "src/assets/icon_close.png");
    }//GEN-LAST:event_btn_closeMouseExited

    private void btn_equalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_equalMouseClicked
        try {
            String eq = ecuacion.getText();
            Mtd_Raices mr = new Mtd_Raices();
            Expresion e = new Expresion();
            int x = mr.clc_raiz(eq);
            lbl_mtd_bi.setText("X=" + mr.mtd_biseccion(x, eq));
            lbl_mtd_fp.setText("X=" + mr.mtd_falsa_posicion(x, eq));
            lbl_mtd_sc1.setText("X=" + mr.mtd_secante_1(x, eq));
            lbl_mtd_sc2.setText("X=" + mr.mtd_secante_1(x, eq));

            XYDataset paresDeDatos = generarDatos(eq, x, mr.mtd_secante_1(x, eq));
            JFreeChart diagrama = crearDiagrama(paresDeDatos);
            chartPanel.setChart(diagrama);

        } catch (Exception ex) {
            Logger.getLogger(Raices.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_equalMouseClicked

    private void ecuacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ecuacionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String eq = ecuacion.getText();
                Mtd_Raices mr = new Mtd_Raices();
                
                Expresion e = new Expresion();
                int x = mr.clc_raiz(eq);
                lbl_mtd_bi.setText("X=" + mr.mtd_biseccion(x, eq));
                lbl_mtd_fp.setText("X=" + mr.mtd_falsa_posicion(x, eq));
                lbl_mtd_sc1.setText("X=" + mr.mtd_secante_1(x, eq));
                lbl_mtd_sc2.setText("X=" + mr.mtd_secante_1(x, eq));
                XYDataset paresDeDatos = generarDatos(eq, x, mr.mtd_secante_1(x, eq));
                JFreeChart diagrama = crearDiagrama(paresDeDatos);
                chartPanel.setChart(diagrama);

            } catch (Exception ex) {
                Logger.getLogger(Raices.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ecuacionKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Raices().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Raices.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_equal;
    private javax.swing.JTextField ecuacion;
    private javax.swing.JPanel grafica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_mtd_bi;
    private javax.swing.JLabel lbl_mtd_fp;
    private javax.swing.JLabel lbl_mtd_sc1;
    private javax.swing.JLabel lbl_mtd_sc2;
    // End of variables declaration//GEN-END:variables
}
